version: '3.8'

services:
    web:
        build: .
        ports:
            - "8080:8080"
        environment:
            - DOTNET_ENVIRONMENT=Production
            - ConnectionStrings__DefaultConnection=Server=db;Database=shoes;User=root;Password=secret
            - ASPNETCORE_URLS=http://+:8080  # Thêm dòng này

        depends_on:
            - db
        volumes:
            - ./Uploads:/app/Uploads 
    db: 
        image: "mysql:8.0"
        container_name: mysql_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: secret
            MYSQL_DATABASE: shoes
        ports:
            - "3307:3306"
        volumes:
            - mysql_data:/var/lib/mysql
            - ./main.sql:/docker-entrypoint-initdb.d/main.sql

volumes:
    mysql_data: